import { describe, expect, test } from "bun:test";
import { createHash } from "node:crypto";
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { assertCodexUpgradeProtocol, CODEX_UPGRADE_SCHEMA_FILES, requiresCodexUpgradeContract } from "../../scripts/codex-upgrade-contract.ts";
import manifest from "../fixtures/codex/0.159.2/manifest.json";

const fixtureRoot = join(import.meta.dir, "../fixtures/codex/0.159.2");
const readFixture = (path: string): string => readFileSync(join(fixtureRoot, `${path}.txt`), "utf8");

describe("pinned Codex 0.159.2 experimental contract", () => {
  test("pins exact release-generated bytes and validates the upgrade surface", () => {
    expect(manifest.version).toBe("0.159.2");
    expect(manifest.commit).toBe("ff6aec96948b70d94983af2641a6b67c94faeff5");
    for (const file of CODEX_UPGRADE_SCHEMA_FILES) {
      expect(createHash("sha256").update(readFixture(file)).digest("hex")).toBe(manifest.sha256[file]);
    }
    expect(() => assertCodexUpgradeProtocol(readFixture)).not.toThrow();
  });

  for (const [path, before, after] of [
    ["v2/CommandExecutionRequestApprovalParams.ts", "approvalId?: string | null", "approvalId?: string"],
    ["v2/CommandExecutionApprovalKind.ts", '"writeStdin"', '"unknownKind"'],
    ["v2/ToolRequestUserInputParams.ts", "isBlocking: boolean", "isBlocking: string"],
    ["v2/ThreadSettings.ts", "effort: ReasoningEffort | null", "effort: ReasoningEffort"],
    ["v2/ThreadResumeParams.ts", "initialTurnsPage?: ThreadResumeInitialTurnsPageParams | null", "removedField?: ThreadResumeInitialTurnsPageParams | null"],
    ["Settings.ts", "reasoning_effort: ReasoningEffort | null", "reasoning_effort: ReasoningEffort"],
  ]) {
    test(`rejects an incompatible ${path} even when comments still mention the field`, () => {
      const original = readFixture(path!);
      expect(original).toContain(before!);
      const broken = original.replace(before!, after!);
      expect(() => assertCodexUpgradeProtocol((file) => file === path ? broken : readFixture(file))).toThrow();
    });
  }

  test("keeps the old floor while requiring release semantics for pinned and future stable versions", () => {
    expect(requiresCodexUpgradeContract("0.145.0")).toBe(false);
    expect(requiresCodexUpgradeContract("0.159.1")).toBe(false);
    expect(requiresCodexUpgradeContract("0.159.2")).toBe(true);
    expect(requiresCodexUpgradeContract("0.160.0")).toBe(true);
    expect(requiresCodexUpgradeContract("1.0.0")).toBe(true);
  });
});
